import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { useSocket } from '../context/SocketContext';
import { useLanguage } from '../context/LanguageContext';
import { LeafletMap } from '../components/LeafletMap';
import {
  ShieldCheck,
  MapPin,
  Clock,
  Phone,
  CheckCircle,
  CreditCard,
  Star,
  Zap,
  Navigation,
  Loader2,
  Wrench,
  Bell,
  Package
} from 'lucide-react';

export function ActiveBookingPage({ booking: initialBooking, onBookingCompleted }) {
  const { isTamil, t, getServiceName, getSubServiceName, getBookingStatusName, getBookingTypeName } = useLanguage();
  const [booking, setBooking] = useState(initialBooking);

  const [invoice, setInvoice] = useState(null);
  const [workerCoords, setWorkerCoords] = useState(null); // [lat, lon]
  const [travelStats, setTravelStats] = useState({ remainingKm: null, etaMinutes: null });
  const [rating, setRating] = useState(5);
  const [feedback, setFeedback] = useState('');
  const [ratingSubmitted, setRatingSubmitted] = useState(false);
  const [paying, setPaying] = useState(false);
  const [billNotice, setBillNotice] = useState(null);

  const socket = useSocket();

  useEffect(() => {
    if (booking?._id) {
      loadDetails();
      if (socket) {
        socket.emit('join:booking', booking._id);
      }
    }
  }, [booking?._id, socket]);

  useEffect(() => {
    if (!socket) return;

    // Listen for worker assignment
    socket.on('booking:worker_assigned', (data) => {
      console.log('[Socket] Worker assigned:', data);
      loadDetails();
    });

    // Listen for lifecycle status changes
    socket.on('booking:status_update', (data) => {
      console.log('[Socket] Status updated:', data);
      setBooking((prev) => (prev ? { ...prev, status: data.status } : prev));
      loadDetails();
    });

    // Listen for bill generation with parts
    socket.on('booking:bill_generated', (data) => {
      console.log('[Socket] Bill generated:', data);
      setBillNotice('Itemized bill with spare parts generated by technician. Ready for payment.');
      loadDetails();
    });

    // Listen for live location tick (GPS or simulation)
    socket.on('worker:location_tick', (data) => {
      if (data.coordinates) {
        setWorkerCoords([data.coordinates[1], data.coordinates[0]]); // Leaflet uses [lat, lon]
        setTravelStats({
          remainingKm: data.remainingKm,
          etaMinutes: data.etaMinutes
        });
      }
    });

    // Listen for arrival
    socket.on('worker:simulated_arrival', () => {
      setBooking((prev) => (prev ? { ...prev, status: 'ARRIVED' } : prev));
    });

    // Payment confirmation
    socket.on('payment:confirmed', () => {
      setBooking((prev) => (prev ? { ...prev, status: 'PAID' } : prev));
      loadDetails();
    });

    return () => {
      socket.off('booking:worker_assigned');
      socket.off('booking:status_update');
      socket.off('booking:bill_generated');
      socket.off('worker:location_tick');
      socket.off('worker:simulated_arrival');
      socket.off('payment:confirmed');
    };
  }, [socket]);

  const loadDetails = async () => {
    if (!booking?._id) return;
    try {
      const res = await api.get(`/customer/bookings/${booking._id}`);
      if (res.data.success) {
        setBooking(res.data.data.booking);
        setInvoice(res.data.data.invoice);
      }
    } catch (err) {
      console.error('[ActiveBooking] Error loading details:', err);
    }
  };

  const handlePayDemo = async () => {
    try {
      setPaying(true);
      const res = await api.post('/customer/payments/demo-pay', {
        bookingId: booking._id,
        paymentMethod: 'DEMO_UPI'
      });
      if (res.data.success) {
        setBooking((prev) => ({ ...prev, status: 'PAID' }));
        setInvoice(res.data.data.invoice);
      }
    } catch (err) {
      alert('Payment failed: ' + err.message);
    } finally {
      setPaying(false);
    }
  };

  const handleRatingSubmit = async () => {
    try {
      await api.post('/customer/ratings', {
        bookingId: booking._id,
        rating,
        reviewTags: ['Punctual', 'Skilled', 'Polite'],
        feedbackText: feedback
      });
      setRatingSubmitted(true);
      if (typeof onBookingCompleted === 'function') {
        onBookingCompleted();
      }
    } catch (err) {
      alert('Rating failed: ' + err.message);
    }
  };

  if (!booking) {
    return (
      <div className="p-8 text-center text-slate-500 space-y-3">
        <MapPin className="w-12 h-12 mx-auto text-slate-700 stroke-1" />
        <p className="font-bold text-sm text-slate-300">No active bookings right now</p>
        <p className="text-xs text-slate-500">Book a service from the home tab to track your technician.</p>
      </div>
    );
  }

  const customerLatLon = booking.customerLocation?.coordinates
    ? [booking.customerLocation.coordinates[1], booking.customerLocation.coordinates[0]]
    : [12.9352, 77.6245];

  const statusBadgeColor = {
    DRAFT: 'bg-slate-800 text-slate-300 border-slate-700',
    SEARCHING: 'bg-amber-500/20 text-amber-400 border-amber-500/30 animate-pulse',
    OFFERED: 'bg-blue-500/20 text-blue-400 border-blue-500/30 animate-pulse',
    CONFIRMED: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    ON_THE_WAY: 'bg-sky-500/20 text-sky-400 border-sky-500/30 animate-pulse',
    ARRIVED: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    IN_PROGRESS: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30',
    COMPLETED: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40 font-black',
    PAID: 'bg-teal-500/20 text-teal-300 border-teal-500/40 font-black'
  }[booking.status] || 'bg-slate-800 text-slate-300 border-slate-700';

  return (
    <div className="p-4 pb-24 space-y-4 text-slate-100">
      {/* Real-time Bill / Status Notification Banner */}
      {billNotice && (
        <div className="bg-gradient-to-r from-sky-950 via-slate-900 to-indigo-950 border border-sky-500/50 rounded-2xl p-3 text-xs flex items-center justify-between text-white animate-in slide-in-from-top duration-300 shadow-lg">
          <div className="flex items-center gap-2">
            <Bell className="w-4 h-4 text-sky-400 animate-bounce" />
            <span className="font-bold">{billNotice}</span>
          </div>
          <button onClick={() => setBillNotice(null)} className="text-slate-400 hover:text-white text-xs px-2">
            ✕
          </button>
        </div>
      )}

      {/* Header Status Bar */}
      <div className="bg-slate-950/80 rounded-2xl p-4 border border-slate-800 shadow-lg flex items-center justify-between">
        <div>
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">{booking.bookingNumber}</span>
          <h2 className="font-black text-white text-base mt-0.5">
            {getServiceName(booking.serviceCategory || booking.serviceId?.category || booking.serviceId?.name || 'plumber')}
          </h2>
          {booking.subSkillId && (
            <p className="text-[11px] text-sky-400 font-bold mt-0.5">
              {getSubServiceName(booking.subSkillId)}
            </p>
          )}
        </div>
        <span className={`text-xs font-black uppercase px-3 py-1.5 rounded-xl border ${statusBadgeColor}`}>
          {getBookingStatusName(booking.status)}
        </span>
      </div>

      {/* Live State Visualizer */}
      {booking.status === 'SEARCHING' && (
        <div className="bg-gradient-to-br from-slate-950 via-slate-900 to-amber-950/30 border border-slate-800 rounded-3xl p-6 text-white text-center space-y-4 shadow-xl">
          <div className="relative w-20 h-20 mx-auto flex items-center justify-center">
            <div className="absolute inset-0 rounded-full border-4 border-amber-500/30 animate-ping" />
            <div className="absolute inset-2 rounded-full border-4 border-amber-500/60 animate-pulse" />
            <div className="w-12 h-12 bg-amber-500 text-slate-950 rounded-full flex items-center justify-center shadow-lg shadow-amber-500/50">
              <Zap className="w-6 h-6 fill-current" />
            </div>
          </div>
          <div>
            <h3 className="font-black text-base text-white">
              {isTamil ? 'முற்போக்கான கூட்டுறவு பணி ஒதுக்கீடு' : 'Progressive Cooperative Dispatch'}
            </h3>
            <p className="text-xs text-slate-400 mt-1 max-w-xs mx-auto">
              {t('ui.scanningRadius', 'Scanning progressive 2dsphere radius (3km → 6km → 12km) and matching verified skills & availability.')}
            </p>
          </div>
        </div>
      )}

      {booking.status === 'OFFERED' && (
        <div className="bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950/40 border border-blue-900/50 rounded-3xl p-6 text-white text-center space-y-3 shadow-xl">
          <div className="w-14 h-14 bg-blue-500 text-slate-950 rounded-full mx-auto flex items-center justify-center animate-bounce shadow-lg shadow-blue-500/50">
            <Clock className="w-7 h-7" />
          </div>
          <h3 className="font-black text-base text-white">
            {t('ui.technicianIdentified', 'Technician Identified!')}
          </h3>
          <p className="text-xs text-blue-300">
            {t('ui.awaitingAcceptance', 'Dispatching 45-second offer countdown to cooperative technician. Awaiting acceptance...')}
          </p>
        </div>
      )}


      {/* Map Tracking View (shown when assigned, en route, arrived, in progress) */}
      {['CONFIRMED', 'ON_THE_WAY', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'PAID'].includes(booking.status) && (
        <div className="space-y-3">
          <div className="relative rounded-2xl overflow-hidden border border-slate-800 shadow-xl">
            <LeafletMap
              customerCoords={customerLatLon}
              workerCoords={workerCoords}
              height="260px"
              zoom={14}
            />

            {/* Travel Stats Overlay */}
            {travelStats.remainingKm !== null && booking.status === 'ON_THE_WAY' && (
              <div className="absolute top-3 left-3 right-3 z-[400] bg-slate-900/95 backdrop-blur-md rounded-2xl p-3 shadow-2xl border border-slate-700/80 flex items-center justify-between text-white">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-xl bg-sky-500/20 text-sky-400 border border-sky-500/30 flex items-center justify-center">
                    <Navigation className="w-4 h-4" />
                  </div>
                  <div>
                    <span className="text-[10px] font-bold uppercase text-slate-400">Technician Distance</span>
                    <p className="text-xs font-black text-white">{travelStats.remainingKm} km away</p>
                  </div>
                </div>
                <div className="text-right">
                  <span className="text-[10px] font-bold uppercase text-slate-400">Est. Arrival</span>
                  <p className="text-xs font-black text-sky-400">~{travelStats.etaMinutes} mins</p>
                </div>
              </div>
            )}
          </div>

          {/* Assigned Worker Details Card */}
          {booking.assignedWorkerId && (
            <div className="bg-slate-950/80 rounded-2xl p-4 border border-slate-800 shadow-md flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-sky-500 to-indigo-500 text-slate-950 flex items-center justify-center font-black text-lg shadow-md">
                  {booking.assignedWorkerId.badgeNumber?.slice(-3) || 'W'}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="font-extrabold text-sm text-white">
                      {booking.assignedWorkerId.userId?.email?.split('@')[0] || 'Suresh Kumar'}
                    </h4>
                    <span className="text-[10px] font-black bg-slate-800 text-sky-400 border border-slate-700 px-1.5 py-0.5 rounded">
                      {booking.assignedWorkerId.badgeNumber}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 text-xs text-slate-400 mt-1">
                    <span className="flex items-center gap-1 font-bold text-amber-400">
                      ★ {booking.assignedWorkerId.rating?.average || 4.9}
                    </span>
                    <span>•</span>
                    <span className="text-emerald-400 font-semibold flex items-center gap-1">
                      <ShieldCheck className="w-3.5 h-3.5" /> Cooperative Certified
                    </span>
                  </div>
                </div>
              </div>

              <a
                href="tel:+919876543210"
                className="w-10 h-10 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 flex items-center justify-center transition shadow-sm border border-emerald-500/30"
              >
                <Phone className="w-4 h-4" />
              </a>
            </div>
          )}
        </div>
      )}

      {/* Invoice & Payment Card (When COMPLETED or PAID) */}
      {invoice && (
        <div className="bg-slate-950/90 rounded-3xl p-5 border border-slate-800 shadow-2xl space-y-4 animate-in fade-in duration-300">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800">
            <div>
              <span className="text-[10px] font-bold uppercase text-slate-500 tracking-wider">Official Cooperative Invoice</span>
              <h3 className="font-black text-white text-sm mt-0.5">{invoice.invoiceNumber}</h3>
            </div>
            <span className={`text-[10px] font-black uppercase px-2.5 py-1 rounded-full border ${
              invoice.status === 'PAID' ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' : 'bg-amber-500/20 text-amber-400 border-amber-500/30'
            }`}>
              {invoice.status}
            </span>
          </div>

          {/* Spare Parts & Materials Section (if added by technician) */}
          {((invoice.parts && invoice.parts.length > 0) || (booking.partsUsed && booking.partsUsed.length > 0)) && (
            <div className="bg-slate-900/90 rounded-2xl p-3.5 border border-slate-800 space-y-2">
              <div className="flex items-center justify-between text-xs font-black text-white">
                <span className="flex items-center gap-1.5 text-sky-400">
                  <Wrench className="w-3.5 h-3.5" /> Spare Parts & Materials Required
                </span>
                <span className="text-emerald-400 font-extrabold">
                  ₹{invoice.partsTotal || booking.pricing?.materialsCost || 0}
                </span>
              </div>
              <div className="divide-y divide-slate-800/60 text-[11px]">
                {(invoice.parts || booking.partsUsed).map((p, idx) => (
                  <div key={idx} className="py-1.5 flex justify-between text-slate-300">
                    <span>{p.name} <span className="text-slate-500">×{p.quantity}</span></span>
                    <span className="font-mono font-bold text-white">₹{p.total || (p.unitCost * p.quantity)}</span>
                  </div>
                ))}
              </div>
              <p className="text-[10px] text-slate-400 italic pt-1 border-t border-slate-800">
                100% of material costs reimbursed directly to technician without platform deduction.
              </p>
            </div>
          )}

          {/* Itemized Cooperative Breakdown */}
          <div className="space-y-2 text-xs">
            <div className="flex justify-between text-slate-400">
              <span>Technician Direct Share (80% Labor {invoice.partsTotal ? `+ ₹${invoice.partsTotal} Parts` : ''})</span>
              <span className="font-bold text-white">₹{invoice.breakdown.workerPayout}</span>
            </div>
            <div className="flex justify-between text-emerald-300 bg-emerald-950/40 p-2.5 rounded-xl border border-emerald-900/60">
              <span className="flex items-center gap-1 font-semibold">
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" /> Cooperative Welfare Reserve (15%)
              </span>
              <span className="font-extrabold text-emerald-400">₹{invoice.breakdown.cooperativeReserve}</span>
            </div>
            <div className="flex justify-between text-slate-400">
              <span>Platform Maintenance (5%)</span>
              <span>₹{invoice.breakdown.infrastructureCut}</span>
            </div>
            <div className="flex justify-between text-base font-black text-white pt-2 border-t border-slate-800">
              <span>Total Guaranteed Amount</span>
              <span className="text-emerald-400 font-black">₹{invoice.breakdown.totalAmount}</span>
            </div>
          </div>

          {invoice.status === 'UNPAID' && (
            <button
              disabled={paying}
              onClick={handlePayDemo}
              className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-400 text-slate-950 font-black text-sm flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/20 hover:from-emerald-400 hover:to-teal-300 transition"
            >
              {paying ? <Loader2 className="w-4 h-4 animate-spin" /> : <CreditCard className="w-4 h-4" />}
              <span>Pay ₹{invoice.breakdown.totalAmount} via Demo UPI</span>
            </button>
          )}

          {invoice.status === 'PAID' && !ratingSubmitted && (
            <div className="bg-slate-900/90 rounded-2xl p-4 border border-slate-800 space-y-3 mt-4">
              <h4 className="text-xs font-black text-white uppercase tracking-wider text-center">
                Rate Cooperative Technician
              </h4>
              <div className="flex justify-center gap-2">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    onClick={() => setRating(star)}
                    className="p-1 transition hover:scale-110"
                  >
                    <Star
                      className={`w-7 h-7 ${
                        star <= rating ? 'text-amber-400 fill-amber-400' : 'text-slate-700'
                      }`}
                    />
                  </button>
                ))}
              </div>
              <input
                type="text"
                placeholder="Share feedback on craftmanship and punctuality..."
                value={feedback}
                onChange={(e) => setFeedback(e.target.value)}
                className="w-full text-xs p-2.5 rounded-xl border border-slate-800 bg-slate-950 text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 transition"
              />
              <button
                onClick={handleRatingSubmit}
                className="w-full py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition"
              >
                Submit Review
              </button>
            </div>
          )}

          {ratingSubmitted && (
            <div className="bg-emerald-950/40 rounded-2xl p-3 border border-emerald-800 text-center text-emerald-300 text-xs font-bold flex items-center justify-center gap-1.5">
              <CheckCircle className="w-4 h-4 text-emerald-400" />
              <span>Thank you! Review credited to technician's reliability record.</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
